services:
  - type: web
    name: grammalecte-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
